# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrillMe', '0002_fooditem_temprature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
