# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 00:14
from __future__ import unicode_literals

import GrillMe.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrillMe', '0007_auto_20170125_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='minutes',
            field=GrillMe.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='seconds',
            field=GrillMe.models.IntegerRangeField(),
        ),
    ]
