# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrillMe', '0008_auto_20170125_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='notes',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
