# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrillMe', '0009_fooditem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
