# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 05:10
from __future__ import unicode_literals

import GrillMe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrillMe', '0010_auto_20170128_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='minutes',
            field=GrillMe.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='seconds',
            field=GrillMe.models.IntegerRangeField(default=0),
        ),
    ]
