# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrillMe', '0011_auto_20170128_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('MEAT', 'MEAT'), ('FISH', 'FISH'), ('VEG', 'VEGETABLE'), ('OTH', 'OTHER')], default=('MEAT', 'MEAT'), max_length=5),
        ),
    ]
